RIDE
====

RIDE is a development environment for Robot Framework test cases.

Installation
============

Using pip

pip install git+https://github.com/zaidpathan1503/RIDE.git@master

Updated to remove references to pybot.bat as these are removed in robot framework 3.1.
